name: CI/CD for Dev Branch

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build --if-present

      - name: Run tests
        run: npm test

  create_pull_request:
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create Pull Request
        run: |
          # Ensure you're on dev branch
          git checkout dev
          
          # Fetch latest branches
          git fetch --all

          # Create pull request using GitHub CLI
          gh pr create --base main --head dev --title "Auto PR from dev to main" --body "Automated PR to merge dev into main" --label "ci-cd"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
